/**
 * Seed PostgreSQL with deterministic demo data generated by the platform's own engines.
 *
 *   pnpm db:seed            # upsert reference data (safe to re-run)
 *   pnpm db:seed --reset    # truncate all tables first (local/dev only)
 *
 * Reference data (users, assets, prices, signals, sports, predictions, the demo paper account)
 * is upserted, so re-running never duplicates it. Event-style tables (model runs, backtests,
 * notifications, audit events) receive a fresh batch on each run, like any recurring job would.
 *
 * Everything written here is SYNTHETIC. The seed never contacts external services.
 */
import { loadEnvConfig } from "@next/env";
import { inArray, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

import * as schema from "@/db/schema";
import { runBacktest } from "@/lib/backtesting/engine";
import { STRATEGIES } from "@/lib/backtesting/strategies";
import { analyzeUniverse } from "@/lib/markets/analysis";
import { DemoMarketDataProvider } from "@/lib/markets/providers/demo-provider";
import { SIGNAL_MODEL_VERSION } from "@/lib/markets/signal-engine";
import { MODEL_CARDS } from "@/lib/models/registry";
import { evaluateSportsModel } from "@/lib/sports/evaluation";
import { FOOTBALL_MODEL_VERSION, predictMatch } from "@/lib/sports/football-model";
import { DEMO_SPORT } from "@/lib/sports/demo-universe";
import { DemoSportsDataProvider } from "@/lib/sports/providers/demo-provider";
import { buildDemoAccount, DEMO_STARTING_CASH } from "@/lib/trade/demo-portfolio";
import { replayLedger } from "@/lib/trade/ledger";
import { buildPortfolioHistory, summarisePortfolio } from "@/lib/trade/portfolio";
import { PostgresPaperTradingStore } from "@/lib/trade/store/postgres-store";

loadEnvConfig(process.cwd());

/** Stable demo identity used by seeded rows. */
export const SEED_USER_ID = "7f2c6a1e-4b8d-4c3a-9e51-5d0b6f3a2c10";

const TABLES_IN_TRUNCATE_ORDER = [
  "audit_events",
  "notifications",
  "backtest_results",
  "backtests",
  "portfolio_snapshots",
  "paper_transactions",
  "paper_positions",
  "paper_orders",
  "paper_accounts",
  "match_predictions",
  "matches",
  "teams",
  "competitions",
  "sports",
  "watchlist_items",
  "watchlists",
  "market_signals",
  "market_prices",
  "model_runs",
  "model_versions",
  "assets",
  "user_preferences",
  "users",
];

function chunk<T>(items: readonly T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

async function main(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.error("✖ DATABASE_URL is not set. Copy .env.example to .env and configure it.");
    process.exit(1);
  }
  const reset = process.argv.includes("--reset");
  const client = postgres(url, { max: 1, prepare: false, onnotice: () => undefined });
  const db = drizzle(client, { schema });
  const started = Date.now();
  const now = new Date();
  const log = (message: string) => console.log(`  • ${message}`);

  try {
    if (reset) {
      await db.execute(
        sql.raw(`TRUNCATE TABLE ${TABLES_IN_TRUNCATE_ORDER.join(", ")} RESTART IDENTITY CASCADE`),
      );
      log("Truncated all tables");
    }

    // ── Users ────────────────────────────────────────────────────────────────────────────────
    await db
      .insert(schema.users)
      .values({ id: SEED_USER_ID, displayName: "Demo Analyst", role: "admin", isDemo: true })
      .onConflictDoUpdate({
        target: schema.users.id,
        set: { displayName: "Demo Analyst", updatedAt: now },
      });
    await db
      .insert(schema.userPreferences)
      .values({
        userId: SEED_USER_ID,
        theme: "system",
        riskProfile: "balanced",
        defaultMarketSymbol: "NVDA",
      })
      .onConflictDoNothing({ target: schema.userPreferences.userId });
    log("Demo user + preferences");

    // ── Models ───────────────────────────────────────────────────────────────────────────────
    const modelRows = await db
      .insert(schema.modelVersions)
      .values(
        MODEL_CARDS.map((card) => ({
          modelKey: card.key,
          version: card.version,
          domain: card.domain,
          name: card.name,
          status: card.status,
          description: card.summary,
          trainingData: card.trainingData,
          featureGroups: card.featureGroups,
          releasedAt: now,
          lastEvaluatedAt: now,
        })),
      )
      .onConflictDoUpdate({
        target: [schema.modelVersions.modelKey, schema.modelVersions.version],
        set: { lastEvaluatedAt: now, updatedAt: now },
      })
      .returning({ id: schema.modelVersions.id, key: schema.modelVersions.modelKey });
    const modelId = new Map(modelRows.map((row) => [row.key, row.id]));
    log(`${modelRows.length} model versions`);

    // ── Markets ──────────────────────────────────────────────────────────────────────────────
    const market = new DemoMarketDataProvider(() => now);
    const profiles = await market.listAssets();
    const assetRows = await db
      .insert(schema.assets)
      .values(
        profiles.map((profile) => ({
          symbol: profile.symbol,
          name: profile.name,
          assetClass: profile.assetClass,
          exchange: profile.exchange,
          currency: profile.currency,
          sector: profile.sector,
          industry: profile.industry,
          description: profile.description,
          metadata: { source: "demo", simulatedPrices: true },
        })),
      )
      .onConflictDoUpdate({ target: schema.assets.symbol, set: { updatedAt: now } })
      .returning({ id: schema.assets.id, symbol: schema.assets.symbol });
    const assetId = new Map(assetRows.map((row) => [row.symbol, row.id]));

    const barsBySymbol = new Map(
      await Promise.all(
        profiles.map(
          async (profile) => [profile.symbol, await market.getDailyBars(profile.symbol)] as const,
        ),
      ),
    );
    const priceRows = profiles.flatMap((profile) =>
      (barsBySymbol.get(profile.symbol) ?? []).slice(-260).map((bar) => ({
        assetId: assetId.get(profile.symbol) as string,
        interval: "1d" as const,
        ts: new Date(`${bar.date}T00:00:00Z`),
        open: bar.open,
        high: bar.high,
        low: bar.low,
        close: bar.close,
        volume: bar.volume,
        source: "demo",
      })),
    );
    for (const batch of chunk(priceRows, 500)) {
      await db.insert(schema.marketPrices).values(batch).onConflictDoNothing();
    }
    log(`${profiles.length} assets, ${priceRows.length} daily bars`);

    const universe = analyzeUniverse(
      profiles.map((profile) => ({ profile, bars: barsBySymbol.get(profile.symbol) ?? [] })),
    );
    const compositeModelId = modelId.get("markets.composite-signal") ?? null;
    const signalRows = universe.assets.flatMap((asset) =>
      asset.features.slice(-30).flatMap((row) =>
        row.composite === null || !row.regime || row.signal === null
          ? []
          : [
              {
                assetId: assetId.get(asset.profile.symbol) as string,
                modelVersionId: compositeModelId,
                asOf: new Date(`${row.date}T21:00:00Z`),
                horizonDays: universe.horizonDays,
                signal: row.signal,
                score: row.composite,
                confidence: row.date === asset.latest.date ? asset.signal.confidence : 0.5,
                probabilityUp: row.date === asset.latest.date ? asset.signal.probabilityUp : 0.5,
                regime: row.regime,
                riskScore: asset.risk.score,
                components:
                  row.date === asset.latest.date
                    ? asset.signal.components.map((c) => ({ ...c }))
                    : [],
                explanation:
                  row.date === asset.latest.date
                    ? asset.signal.explanation
                    : `Historical ${row.signal} signal (score ${row.composite.toFixed(2)}).`,
              },
            ],
      ),
    );
    for (const batch of chunk(signalRows, 200)) {
      await db
        .insert(schema.marketSignals)
        .values(batch)
        .onConflictDoNothing({
          target: [
            schema.marketSignals.assetId,
            schema.marketSignals.asOf,
            schema.marketSignals.horizonDays,
          ],
        });
    }
    log(`${signalRows.length} market signals (${SIGNAL_MODEL_VERSION})`);

    // ── Watchlist ────────────────────────────────────────────────────────────────────────────
    const [watchlist] = await db
      .insert(schema.watchlists)
      .values({ userId: SEED_USER_ID, name: "Core watchlist", isDefault: true })
      .onConflictDoUpdate({
        target: [schema.watchlists.userId, schema.watchlists.name],
        set: { updatedAt: now },
      })
      .returning({ id: schema.watchlists.id });
    if (watchlist) {
      await db
        .insert(schema.watchlistItems)
        .values(
          ["NVDA", "MSFT", "AAPL", "TSLA", "SPY"].map((symbol, position) => ({
            watchlistId: watchlist.id,
            assetId: assetId.get(symbol) as string,
            position,
          })),
        )
        .onConflictDoNothing();
    }
    log("Default watchlist");

    // ── Sports ───────────────────────────────────────────────────────────────────────────────
    const sportsProvider = new DemoSportsDataProvider(() => now);
    const [sport] = await db
      .insert(schema.sports)
      .values({ key: DEMO_SPORT.key, name: DEMO_SPORT.name })
      .onConflictDoUpdate({ target: schema.sports.key, set: { updatedAt: now } })
      .returning({ id: schema.sports.id });
    if (!sport) throw new Error("Failed to upsert sport");

    const competitions = await sportsProvider.listCompetitions();
    const competitionRows = await db
      .insert(schema.competitions)
      .values(
        competitions.map((competition) => ({
          sportId: sport.id,
          key: competition.key,
          name: competition.name,
          region: competition.region,
          season: competition.season,
          baselineGoals: competition.baselineGoals,
          homeAdvantage: competition.homeAdvantage,
        })),
      )
      .onConflictDoUpdate({
        target: [schema.competitions.key, schema.competitions.season],
        set: { updatedAt: now },
      })
      .returning({ id: schema.competitions.id, key: schema.competitions.key });
    const competitionId = new Map(competitionRows.map((row) => [row.key, row.id]));

    const teams = await sportsProvider.listTeams();
    const teamRows = await db
      .insert(schema.teams)
      .values(
        teams.map((team) => ({
          sportId: sport.id,
          competitionId: competitionId.get(team.competitionKey) ?? null,
          key: team.key,
          name: team.name,
          shortName: team.shortName,
          code: team.code,
          city: team.city,
          metadata: { venue: team.venue, fictional: true },
        })),
      )
      .onConflictDoUpdate({ target: schema.teams.key, set: { updatedAt: now } })
      .returning({ id: schema.teams.id, key: schema.teams.key });
    const teamId = new Map(teamRows.map((row) => [row.key, row.id]));

    const matches = await sportsProvider.listMatches();
    const matchRows: { id: string; ref: string }[] = [];
    for (const batch of chunk(matches, 100)) {
      const rows = await db
        .insert(schema.matches)
        .values(
          batch.map((match) => ({
            competitionId: competitionId.get(match.competitionKey) as string,
            homeTeamId: teamId.get(match.homeTeam.key) as string,
            awayTeamId: teamId.get(match.awayTeam.key) as string,
            kickoffAt: new Date(match.kickoffAt),
            status: match.status,
            matchday: match.round,
            venue: match.venue,
            homeScore: match.score?.home ?? null,
            awayScore: match.score?.away ?? null,
            externalRef: match.id,
            context: { ...match.context, xg: match.xg },
          })),
        )
        .onConflictDoUpdate({
          target: schema.matches.externalRef,
          set: {
            kickoffAt: sql`excluded.kickoff_at`,
            status: sql`excluded.status`,
            homeScore: sql`excluded.home_score`,
            awayScore: sql`excluded.away_score`,
            context: sql`excluded.context`,
            updatedAt: now,
          },
        })
        .returning({ id: schema.matches.id, ref: schema.matches.externalRef });
      matchRows.push(...rows);
    }
    const matchId = new Map(matchRows.map((row) => [row.ref, row.id]));

    await db
      .delete(schema.matchPredictions)
      .where(inArray(schema.matchPredictions.matchId, [...matchId.values()]));
    const footballModelId = modelId.get("sports.poisson-dixon-coles") ?? null;
    const predictionRows = matches.map((match) => {
      const prediction = predictMatch(match.modelInputs);
      const kickoff = new Date(match.kickoffAt);
      return {
        matchId: matchId.get(match.id) as string,
        modelVersionId: footballModelId,
        generatedAt:
          match.status === "scheduled" ? now : new Date(kickoff.getTime() - 2 * 3_600_000),
        lambdaHome: prediction.lambdaHome,
        lambdaAway: prediction.lambdaAway,
        pHome: prediction.outcome.home,
        pDraw: prediction.outcome.draw,
        pAway: prediction.outcome.away,
        pOver15: prediction.markets.over15,
        pOver25: prediction.markets.over25,
        pOver35: prediction.markets.over35,
        pUnder25: prediction.markets.under25,
        pBtts: prediction.markets.bttsYes,
        pCleanSheetHome: prediction.markets.cleanSheetHome,
        pCleanSheetAway: prediction.markets.cleanSheetAway,
        confidence: prediction.confidence,
        uncertainty: prediction.uncertainty,
        scoreMatrix: prediction.scoreMatrix.map((row) => row.map((p) => Math.round(p * 1e6) / 1e6)),
        topScorelines: prediction.topScorelines,
        inputs: { ...match.modelInputs, modelVersion: FOOTBALL_MODEL_VERSION },
      };
    });
    for (const batch of chunk(predictionRows, 100)) {
      await db.insert(schema.matchPredictions).values(batch);
    }
    log(
      `${competitions.length} competitions, ${teams.length} teams, ${matches.length} matches + predictions`,
    );

    // ── Paper account ────────────────────────────────────────────────────────────────────────
    const store = new PostgresPaperTradingStore(db);
    const session = market.getSession();
    const existing = await store.load(SEED_USER_ID);
    if (!existing) {
      await store.mutate(SEED_USER_ID, () => {
        const account = buildDemoAccount({
          accountId: SEED_USER_ID,
          ownerId: SEED_USER_ID,
          lastCompletedDate: session.lastCompletedDate,
          barsBySymbol,
        });
        return {
          next: account,
          appended: account.orders,
          created: true,
          reset: false,
          result: account,
        };
      });
    }
    const account = await store.load(SEED_USER_ID);
    if (account) {
      const history = buildPortfolioHistory(account, barsBySymbol, {
        from: account.createdAt.slice(0, 10),
        to: session.lastCompletedDate,
      });
      const snapshotRows = history.map((point) => {
        const ledger = replayLedger(
          account.startingCash,
          account.orders.filter((o) => (o.filledAt ?? o.requestedAt).slice(0, 10) <= point.date),
        );
        const prices = new Map(
          [...ledger.holdings.keys()].map((symbol) => {
            const bar = (barsBySymbol.get(symbol) ?? []).find((b) => b.date === point.date);
            return [symbol, { price: bar?.close ?? 0, previousClose: bar?.close ?? 0 }] as const;
          }),
        );
        const { summary } = summarisePortfolio(account, ledger, prices);
        return {
          accountId: account.id,
          asOf: new Date(`${point.date}T21:00:00Z`),
          cash: summary.cash,
          marketValue: summary.marketValue,
          totalValue: summary.totalValue,
          investedCapital: summary.investedCapital,
          unrealizedPnl: summary.unrealizedPnl,
          realizedPnl: summary.realizedPnl,
          riskLevel: "MODERATE" as const,
          metrics: { drawdown: point.drawdown },
        };
      });
      for (const batch of chunk(snapshotRows, 200)) {
        await db.insert(schema.portfolioSnapshots).values(batch).onConflictDoNothing();
      }
      log(
        `Paper account (${account.orders.length} orders, starting cash ${DEMO_STARTING_CASH}) + ${snapshotRows.length} snapshots`,
      );
    }

    // ── Model evaluation runs ────────────────────────────────────────────────────────────────
    const sportsEvaluation = evaluateSportsModel(
      matches.filter((match) => match.status === "finished"),
    );
    const toJson = (value: unknown) => JSON.parse(JSON.stringify(value)) as Record<string, unknown>;
    const runRows: { modelVersionId: string; metrics: Record<string, unknown> }[] = [];
    if (compositeModelId) {
      runRows.push({
        modelVersionId: compositeModelId,
        metrics: toJson({ ...universe.evaluation, reliability: undefined }),
      });
    }
    if (footballModelId) {
      runRows.push({
        modelVersionId: footballModelId,
        metrics: toJson({ ...sportsEvaluation, recent: undefined, reliability: undefined }),
      });
    }
    await db.insert(schema.modelRuns).values(
      runRows.map((row) => ({
        modelVersionId: row.modelVersionId,
        runType: "evaluation" as const,
        status: "succeeded" as const,
        startedAt: new Date(now.getTime() - 90_000),
        finishedAt: now,
        parameters: { source: "db:seed" },
        metrics: row.metrics,
      })),
    );
    log(`${runRows.length} model evaluation runs`);

    // ── Backtests ────────────────────────────────────────────────────────────────────────────
    const endDate = session.lastCompletedDate;
    const startDate = `${Number(endDate.slice(0, 4)) - 2}${endDate.slice(4)}`;
    for (const [symbol, strategy] of [
      ["NVDA", "composite"],
      ["NVDA", "momentum"],
      ["SPY", "sma_crossover"],
    ] as const) {
      const result = runBacktest(barsBySymbol.get(symbol) ?? [], {
        symbol,
        strategy,
        startDate,
        endDate,
        initialCapital: 100_000,
        feeBps: 5,
        slippageBps: 5,
      });
      const [backtest] = await db
        .insert(schema.backtests)
        .values({
          userId: SEED_USER_ID,
          assetId: assetId.get(symbol) ?? null,
          symbol,
          strategy,
          parameters: STRATEGIES[strategy].parameters,
          startDate,
          endDate,
          initialCapital: 100_000,
          feeBps: 5,
          slippageBps: 5,
          status: "succeeded",
        })
        .returning({ id: schema.backtests.id });
      if (!backtest) continue;
      const m = result.metrics;
      await db.insert(schema.backtestResults).values({
        backtestId: backtest.id,
        endingCapital: m.endingCapital,
        totalReturn: m.totalReturn,
        benchmarkReturn: m.benchmarkReturn,
        tradesCount: m.trades,
        winRate: m.winRate,
        maxDrawdown: m.maxDrawdown,
        volatility: m.volatility,
        sharpe: m.sharpe,
        exposure: m.exposure,
        equityCurve: result.equityCurve.map(({ date, equity, benchmark }) => ({
          date,
          equity,
          benchmark,
        })),
        trades: result.trades.map((trade) => ({ ...trade })),
      });
    }
    log("3 sample backtests");

    // ── Notifications & audit ────────────────────────────────────────────────────────────────
    const top = [...universe.assets].sort((a, b) => b.signal.confidence - a.signal.confidence)[0];
    await db.insert(schema.notifications).values([
      {
        userId: SEED_USER_ID,
        type: "signal",
        severity: "info",
        title: top ? `${top.profile.symbol} signal: ${top.signal.signal}` : "Signals refreshed",
        body: top
          ? `Composite score ${top.signal.score.toFixed(2)}, confidence ${(top.signal.confidence * 100).toFixed(0)}%.`
          : "Daily signals refreshed.",
        link: top ? `/markets/${top.profile.symbol}` : "/markets",
      },
      {
        userId: SEED_USER_ID,
        type: "model",
        severity: "success",
        title: "Model evaluation completed",
        body: `Football model accuracy ${((sportsEvaluation.accuracy ?? 0) * 100).toFixed(0)}% on ${sportsEvaluation.matches} finished matches.`,
        link: "/model-lab",
      },
      {
        userId: SEED_USER_ID,
        type: "system",
        severity: "info",
        title: "Demo data seeded",
        body: "All prices, fixtures and results are synthetic demo data.",
        link: "/admin",
      },
    ]);
    await db.insert(schema.auditEvents).values([
      {
        actorType: "system",
        actorId: "db:seed",
        action: "model.evaluated",
        resourceType: "model_version",
        resourceId: compositeModelId ?? "n/a",
        outcome: "success",
        metadata: { source: "db:seed" },
      },
      {
        actorType: "system",
        actorId: "db:seed",
        action: "paper_account.created",
        resourceType: "paper_account",
        resourceId: SEED_USER_ID,
        outcome: "success",
        metadata: { source: "db:seed" },
      },
    ]);
    log("Notifications + audit events");

    console.log(`✔ Seed complete in ${((Date.now() - started) / 1000).toFixed(1)}s`);
  } finally {
    await client.end({ timeout: 5 });
  }
}

main().catch((error: unknown) => {
  console.error("✖ Seed failed:", error instanceof Error ? error.message : error);
  if (error instanceof Error && error.cause) console.error(error.cause);
  process.exit(1);
});
