"""Cross-language parity: the Python ports must reproduce the TypeScript engines.

Fixtures are generated by `pnpm parity:fixtures` (scripts/generate-parity-fixtures.ts) from the
web app's engines; the web test suite fails if they go stale.
"""

from __future__ import annotations

import math

import pytest

from app.features.signals import build_feature_rows, compute_confidence
from app.schemas.sports import SportsPredictRequest
from app.services.backtest import Bar, run_backtest
from app.services.sports import predict_sports

REL = 1e-9
ABS = 1e-9


def close(actual: float | None, expected: float | None, abs_tol: float = ABS) -> bool:
    if actual is None or expected is None:
        return actual is expected
    return math.isclose(actual, expected, rel_tol=REL, abs_tol=abs_tol)


def test_fixture_version(parity: dict) -> None:
    assert parity["version"] == 1


def test_sports_parity(parity: dict) -> None:
    for case in parity["sports"]:
        response = predict_sports(SportsPredictRequest.model_validate(case["request"])).model_dump()
        expected = case["expected"]
        name = case["name"]
        for key in (
            "lambda_home",
            "lambda_away",
            "rho",
            "truncated_mass",
            "outcome_entropy",
            "data_quality",
            "confidence",
        ):
            assert close(response[key], expected[key]), (name, key, response[key], expected[key])
        assert response["max_goals"] == expected["max_goals"]
        assert response["uncertainty"] == expected["uncertainty"], name
        assert response["most_likely_outcome"] == expected["most_likely_outcome"], name
        for key, value in expected["outcome"].items():
            assert close(response["outcome"][key], value), (name, key)
        for key, value in expected["markets"].items():
            assert close(response["markets"][key], value), (name, key)
        for actual_row, expected_row in zip(response["score_matrix"], expected["score_matrix"], strict=True):
            for actual, value in zip(actual_row, expected_row, strict=True):
                assert close(actual, value), name
        for actual, value in zip(response["top_scorelines"], expected["top_scorelines"], strict=True):
            assert (actual["home"], actual["away"]) == (value["home"], value["away"]), name
            assert close(actual["probability"], value["probability"]), name
        for actual, value in zip(response["factors"], expected["factors"], strict=True):
            assert actual["key"] == value["key"]
            assert close(actual["home"], value["home"]) and close(actual["away"], value["away"]), (
                name,
                value["key"],
            )


@pytest.mark.parametrize("index", [0, 1])
def test_market_parity(parity: dict, index: int) -> None:
    case = parity["markets"][index]
    bars = case["bars"]
    rows = build_feature_rows(
        [b["date"] for b in bars], [b["close"] for b in bars], [b["volume"] for b in bars]
    )
    latest = rows[-1]
    expected = case["expected"]["latest"]
    assert latest.date == expected["date"]
    for attribute, key in [
        ("sma20", "sma20"),
        ("sma50", "sma50"),
        ("ema20", "ema20"),
        ("rsi14", "rsi14"),
        ("macd", "macd"),
        ("macd_signal", "macd_signal"),
        ("macd_histogram", "macd_histogram"),
        ("momentum21", "momentum21"),
        ("momentum63", "momentum63"),
        ("volatility20", "volatility20"),
        ("volatility63", "volatility63"),
        ("volatility_percentile", "volatility_percentile"),
        ("trend_strength", "trend_strength"),
        ("drawdown", "drawdown"),
        ("composite", "composite"),
    ]:
        assert close(getattr(latest, attribute), expected[key], abs_tol=1e-8), (case["name"], key)
    assert latest.regime == expected["regime"]
    assert latest.signal == expected["signal"]
    for key, value in expected["scores"].items():
        assert close(latest.scores[key], value, abs_tol=1e-8), key
    assert close(
        compute_confidence(latest.composite, latest.signal, latest.scores, latest.regime),
        expected["confidence"],
    )
    by_date = {row.date: row for row in rows}
    for point in case["expected"]["recent"]:
        row = by_date[point["date"]]
        assert row.signal == point["signal"], point["date"]
        assert close(row.composite, point["composite"], abs_tol=1e-8), point["date"]


def test_backtest_parity(parity: dict) -> None:
    bars = [
        Bar(b["date"], b["open"], b["high"], b["low"], b["close"], b["volume"])
        for b in parity["backtest"]["bars"]
    ]
    for case in parity["backtest"]["cases"]:
        request = case["request"]
        result = run_backtest(
            bars,
            strategy_id=request["strategy"],
            start_date=request["start_date"],
            end_date=request["end_date"],
            initial_capital=request["initial_capital"],
            fee_bps=request["fee_bps"],
            slippage_bps=request["slippage_bps"],
        )
        expected = case["expected"]
        camel = {
            "starting_capital": "startingCapital",
            "ending_capital": "endingCapital",
            "total_return": "totalReturn",
            "benchmark_return": "benchmarkReturn",
            "excess_return": "excessReturn",
            "cagr": "cagr",
            "trades": "trades",
            "win_rate": "winRate",
            "average_trade_return": "averageTradeReturn",
            "max_drawdown": "maxDrawdown",
            "benchmark_max_drawdown": "benchmarkMaxDrawdown",
            "volatility": "volatility",
            "sharpe": "sharpe",
            "benchmark_sharpe": "benchmarkSharpe",
            "exposure": "exposure",
            "fees_paid": "feesPaid",
            "trading_days": "tradingDays",
        }
        for snake, key in camel.items():
            assert close(result["metrics"][snake], expected["metrics"][key], abs_tol=1e-6), (
                case["name"],
                snake,
            )
        assert len(result["trades"]) == len(expected["trades"]), case["name"]
        for actual, trade in zip(result["trades"], expected["trades"], strict=True):
            assert actual["entry_date"] == trade["entryDate"]
            assert actual["exit_date"] == trade["exitDate"]
            assert actual["shares"] == trade["shares"]
            assert close(actual["pnl"], trade["pnl"], abs_tol=1e-6)
        assert result["equity_curve"][0] == expected["equity_first"]
        assert result["equity_curve"][-1] == expected["equity_last"]
        assert len(result["warnings"]) == expected["warnings"]
